package legacy.gui.table;

import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.JTable;
import legacy.database.Criteria;
import legacy.database.User;

public class ClientsTable extends JPanel {

    private static final Logger log = Logger.getLogger(ClientsTable.class.getName());
    private ClientsTableModel m = new ClientsTableModel();

    public ClientsTable() {
        initComponents();
        m = new ClientsTableModel();
        table.setModel(m);
    }

    private void setClientsBean() {
        int row = table.getSelectedRow();
        String s = table.getValueAt(row, 0).toString();
        int i = Integer.parseInt(s);
        this.firePropertyChange("client", null, i);
    }

    public void select(Criteria c) {
        table.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String[]{
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        m = new ClientsTableModel();
        m.select(c);
        table.setModel(m);
    }

    public int getId() throws ArrayIndexOutOfBoundsException {
        int row = table.getSelectedRow();
        String s = table.getValueAt(row, 0).toString();
        int id = Integer.parseInt(s);
        return id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setLayout(new java.awt.GridLayout(1, 0));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        setClientsBean();
    }//GEN-LAST:event_tableMouseClicked

    private void tableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableKeyReleased
        setClientsBean();
    }//GEN-LAST:event_tableKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    void setUser(User user) {
        log.fine(user.toString());
    }

}
