package legacy.gui.panels;

import legacy.gui.panels.Details;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;
import legacy.database.Clients;
import legacy.database.User;
import legacy.database.UserRole;
import legacy.gui.table.LegacyTab;

public class TabsPane extends javax.swing.JPanel {

    private static final Logger log = Logger.getLogger(TabsPane.class.getName());
    //private SelectByStatus t = new SelectByStatus();
    private LegacyTab legacyTab;
    private Details details;
    private User user;

    private TabsPane() {
        List<UserRole> roles = new ArrayList<>();
        roles.add(UserRole.OPENER);
        user = new User("foo", "bar");
        initComponents();
        legacyTab = new LegacyTab(user);
        details = new Details(user);
    }

    public TabsPane(User user) {
        this.user = user;
        initComponents();
        legacyTab = new LegacyTab(user);
        details = new Details(user);
        if (user.getRoles().contains(UserRole.OPENER)) {
            tabs.add("create", details);
        } else {
            tabs.add("legacy", legacyTab);
            tabs.add("details", details);
        }
        rowSelected();
    }

    public void setClient(Clients b) {
        details.setB(b);
    }

    private void rowSelected() {
        legacyTab.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            @Override
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                if ("client".equals(evt.getPropertyName())) {
                    Clients b = (Clients) evt.getNewValue();
                    log.fine(b.toString());
//                    JDialog dialog = new JDialog(MainFrame.getInstance());

                    setClient(b);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());
        add(tabs, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables

}
